/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectWiCaDi;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Map;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.Box;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;


/**
 *
 * @author sandalu
 */
public class AdvancedCalculator extends javax.swing.JFrame {

    //Multi-Variable values
    private String vname1;
    private String vvalue1;
    private boolean flag1 = false;
    
    private String vname2;
    private String vvalue2;
    private boolean flag2 = false;
    
    private String vname3;
    private String vvalue3;
    private boolean flag3 = false;
    
    //Integration
    private double upperbound;
    private double lowerbound;
    private char variablebound;
    private boolean Integrationflag = false;
    /**
     * Creates new form AdvancedCalculator
     */
    public AdvancedCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        zero = new javax.swing.JButton();
        decimal_point = new javax.swing.JButton();
        pie = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        factorial = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        LOG = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        multipe = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        modification = new javax.swing.JButton();
        intergration = new javax.swing.JButton();
        e_value = new javax.swing.JButton();
        square = new javax.swing.JButton();
        ten_power = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        cude = new javax.swing.JButton();
        any_power = new javax.swing.JButton();
        root = new javax.swing.JButton();
        precentage = new javax.swing.JButton();
        bracket_O = new javax.swing.JButton();
        bracket_C = new javax.swing.JButton();
        up_down = new javax.swing.JButton();
        graph_button = new javax.swing.JButton();
        manage_v = new javax.swing.JButton();
        clear_entry = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        load = new javax.swing.JButton();
        Display_out = new javax.swing.JTextField();
        Display_in = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        standard = new javax.swing.JButton();
        advance = new javax.swing.JButton();
        graph = new javax.swing.JButton();
        vscroll = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        var_meg = new javax.swing.JLabel();
        var_meg1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hscroll = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 750));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 750));

        zero.setBackground(new java.awt.Color(31, 31, 31));
        zero.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        zero.setForeground(new java.awt.Color(255, 255, 255));
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        decimal_point.setBackground(new java.awt.Color(204, 204, 204));
        decimal_point.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        decimal_point.setText(".");
        decimal_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimal_pointActionPerformed(evt);
            }
        });

        pie.setBackground(new java.awt.Color(204, 204, 204));
        pie.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pie.setText(" π");
        pie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        delete.setText("DEL");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(204, 204, 204));
        equal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(31, 31, 31));
        one.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        one.setForeground(new java.awt.Color(255, 255, 255));
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(31, 31, 31));
        two.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        two.setForeground(new java.awt.Color(255, 255, 255));
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(31, 31, 31));
        three.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        three.setForeground(new java.awt.Color(255, 255, 255));
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(204, 204, 204));
        plus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        factorial.setBackground(new java.awt.Color(204, 204, 204));
        factorial.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        factorial.setText("n!");
        factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(31, 31, 31));
        four.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        four.setForeground(new java.awt.Color(255, 255, 255));
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(31, 31, 31));
        five.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        five.setForeground(new java.awt.Color(255, 255, 255));
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(31, 31, 31));
        six.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        six.setForeground(new java.awt.Color(255, 255, 255));
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        minus.setBackground(new java.awt.Color(204, 204, 204));
        minus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        LOG.setBackground(new java.awt.Color(204, 204, 204));
        LOG.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LOG.setText("ln");
        LOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(31, 31, 31));
        seven.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        seven.setForeground(new java.awt.Color(255, 255, 255));
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(31, 31, 31));
        eight.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        eight.setForeground(new java.awt.Color(255, 255, 255));
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(31, 31, 31));
        nine.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        nine.setForeground(new java.awt.Color(255, 255, 255));
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        multipe.setBackground(new java.awt.Color(204, 204, 204));
        multipe.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        multipe.setText("*");
        multipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipeActionPerformed(evt);
            }
        });

        divide.setBackground(new java.awt.Color(204, 204, 204));
        divide.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        modification.setBackground(new java.awt.Color(204, 204, 204));
        modification.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modification.setText("MOD");
        modification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationActionPerformed(evt);
            }
        });

        intergration.setBackground(new java.awt.Color(204, 204, 204));
        intergration.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        intergration.setText(" ʃ ");
        intergration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intergrationActionPerformed(evt);
            }
        });

        e_value.setBackground(new java.awt.Color(204, 204, 204));
        e_value.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        e_value.setText("e");
        e_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_valueActionPerformed(evt);
            }
        });

        square.setBackground(new java.awt.Color(204, 204, 204));
        square.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        square.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/1608861-64 (1).png"))); // NOI18N
        square.setActionCommand("sqr");
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });

        ten_power.setBackground(new java.awt.Color(204, 204, 204));
        ten_power.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ten_power.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/10x.png"))); // NOI18N
        ten_power.setActionCommand("10ᴧ");
        ten_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten_powerActionPerformed(evt);
            }
        });

        sin.setBackground(new java.awt.Color(204, 204, 204));
        sin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setBackground(new java.awt.Color(204, 204, 204));
        cos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setBackground(new java.awt.Color(204, 204, 204));
        tan.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        cude.setBackground(new java.awt.Color(204, 204, 204));
        cude.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/x3.png"))); // NOI18N
        cude.setActionCommand("cude");
        cude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cudeActionPerformed(evt);
            }
        });

        any_power.setBackground(new java.awt.Color(204, 204, 204));
        any_power.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        any_power.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/xn.png"))); // NOI18N
        any_power.setActionCommand("ᴧ");
        any_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                any_powerActionPerformed(evt);
            }
        });

        root.setBackground(new java.awt.Color(204, 204, 204));
        root.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        root.setText("√ ");
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootActionPerformed(evt);
            }
        });

        precentage.setBackground(new java.awt.Color(204, 204, 204));
        precentage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        precentage.setText("%");
        precentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precentageActionPerformed(evt);
            }
        });

        bracket_O.setBackground(new java.awt.Color(204, 204, 204));
        bracket_O.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        bracket_O.setText(")");
        bracket_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracket_OActionPerformed(evt);
            }
        });

        bracket_C.setBackground(new java.awt.Color(204, 204, 204));
        bracket_C.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bracket_C.setText("(");
        bracket_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracket_CActionPerformed(evt);
            }
        });

        up_down.setBackground(new java.awt.Color(204, 204, 204));
        up_down.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        up_down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/x1.png"))); // NOI18N
        up_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_downActionPerformed(evt);
            }
        });

        graph_button.setBackground(new java.awt.Color(204, 204, 204));
        graph_button.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        graph_button.setText("Graph");
        graph_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graph_buttonActionPerformed(evt);
            }
        });

        manage_v.setBackground(new java.awt.Color(31, 31, 31));
        manage_v.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        manage_v.setForeground(new java.awt.Color(255, 255, 255));
        manage_v.setText("Add Variable");
        manage_v.setToolTipText("");
        manage_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_vActionPerformed(evt);
            }
        });

        clear_entry.setBackground(new java.awt.Color(31, 31, 31));
        clear_entry.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clear_entry.setForeground(new java.awt.Color(255, 255, 255));
        clear_entry.setText("CE");
        clear_entry.setToolTipText("");
        clear_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_entryActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(31, 31, 31));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(31, 31, 31));
        clear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("c");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        load.setBackground(new java.awt.Color(31, 31, 31));
        load.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        load.setForeground(new java.awt.Color(255, 255, 255));
        load.setText("LOAD");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        Display_out.setEditable(false);
        Display_out.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        Display_out.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display_out.setToolTipText("");

        Display_in.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        Display_in.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display_inActionPerformed(evt);
            }
        });
        Display_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Display_inKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/font.jpg"))); // NOI18N
        jLabel4.setName(""); // NOI18N

        standard.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        standard.setText("Basic Calculator");
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        advance.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        advance.setText("Advanced Calculator");
        advance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceActionPerformed(evt);
            }
        });

        graph.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        graph.setText("Graph Display");
        graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        vscroll.setViewportView(jTextArea1);

        var_meg.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        var_meg.setForeground(new java.awt.Color(255, 255, 255));
        var_meg.setText("         Variable Values");

        var_meg1.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        var_meg1.setForeground(new java.awt.Color(255, 255, 255));
        var_meg1.setText("                   History");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" (Use KeyBoard to Enter Varibles)");

        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("--No history to show--");
        jTextArea2.setBorder(null);
        hscroll.setViewportView(jTextArea2);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("load to file");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(79, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("save to file");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(79, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/pgg.jpg"))); // NOI18N

        jButton4.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/informauion.jpg"))); // NOI18N
        jButton6.setToolTipText("Assigned variables should exclude\n Java keywords and saved formula names.");
        jButton6.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(standard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245)
                        .addComponent(jLabel4)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addComponent(Display_out, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Display_in, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(modification, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(intergration, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(e_value, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(ten_power, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(multipe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(LOG, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(decimal_point, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(pie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(load, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(precentage, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bracket_C, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(up_down, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(graph_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bracket_O, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear_entry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(5, 5, 5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(cude, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(manage_v, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(5, 5, 5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(any_power, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hscroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(var_meg1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(var_meg, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(Display_in, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Display_out, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(var_meg)
                                    .addComponent(jButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vscroll)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(var_meg1)
                        .addGap(15, 15, 15)
                        .addComponent(hscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(manage_v, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clear_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(load, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cude, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(any_power, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(graph_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ten_power, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(up_down, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(e_value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(intergration, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(multipe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bracket_C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LOG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bracket_O, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(precentage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(decimal_point, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        String Enternumber = Display_in.getText() + "0";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_zeroActionPerformed

    private void decimal_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimal_pointActionPerformed
        String Enternumber = Display_in.getText() + ".";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_decimal_pointActionPerformed

    private void pieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieActionPerformed
        String Enternumber = Display_in.getText() + "π";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_pieActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        Display_in.setText (Display_in.getText ().substring (0, Display_in.getText ().length () - 1));
    }//GEN-LAST:event_deleteActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
try {
       
    
    //functionimplementation
    String key;
    String formula = Display_in.getText();
    String newFormula ="";
    String s="";
    Vector<Character> tempvec = new Vector<>();
    Vector<String> vec = new Vector<>();
    boolean savedFormulaFlag = false;
    boolean savedFormulaFlag1 = false;

    FormulaElement f = new FormulaElement() {};
        
    if(this.Integrationflag == false){
        //Check for saved formulas
        for(int i=0;i<formula.length();i++){
            savedFormulaFlag1 = false;
            for(Map.Entry entry: temp.entrySet()){
                key = (String) entry.getKey();
                if(formula.charAt(i)== key.charAt(0)){
                    i=i+2;
                    while(formula.charAt(i)!=')'){
                        tempvec.add(formula.charAt(i));
                        i++;
                    }
                    
                    for(int j=0;j<tempvec.size();j++){
                        s = s+tempvec.get(j);
                    }
                    
                    StringTokenizer tokenizer = new StringTokenizer(s, "=, ", false);
                    while (tokenizer.hasMoreTokens()) {
                        String token = tokenizer.nextToken();
                        vec.add(token);
                    }
                    
                              
                    newFormula = newFormula+"("+temp.get(key)+")";
                    savedFormulaFlag1 = true;
                    savedFormulaFlag =true;
                } 
                
            }
            
            if (savedFormulaFlag1==false){
            newFormula= newFormula+formula.charAt(i);
            }
        }
        
        if(savedFormulaFlag==false){
            newFormula = formula;
        }
        
        //Create formulaElement object        
        FormulaElement f2 = f.parseFormula(newFormula, 0, 0,'y');
        
        //set multivariable values
        if(this.flag1 == true){
            f2.setVariableValue(vname1, Double.valueOf(vvalue1));
            if(this.flag2 == true){
                f2.setVariableValue(vname2, Double.valueOf(vvalue2));
                if(this.flag3 == true){
                    f2.setVariableValue(vname3, Double.valueOf(vvalue3));
                }
            }
        }
        //set formula variable values
            if(vec.size()==0){
                //****
            } else if(vec.size()==1){
                f2.setVariableValue("x", Double.valueOf(vec.get(0)));
            }else if(vec.size()>1){
                f2.setVariableValue("x", Double.valueOf(vec.get(1)));
                f2.setVariableValue("y", Double.valueOf(vec.get(3)));
            }
            
        //set java keywords
        f2.setVariableValue("e", 2.718);
        f2.setVariableValue("π", 3.141); 
        
        
        String answer = Float.toString((float) f2.evaluate());
            Display_out.setText(answer);
            
    }           

       
       else if(this.Integrationflag == true){
            FormulaElement f2 = f.parseFormula(formula, upperbound, lowerbound, variablebound);
       
            f2.setVariableValue("e", 2.718);
            f2.setVariableValue("π", 3.141);    
       
            if(this.flag1 == true){
                f2.setVariableValue(vname1, Double.valueOf(vvalue1));
                if(this.flag2 == true){
                    f2.setVariableValue(vname2, Double.valueOf(vvalue2));
                    if(this.flag2 == true){
                        f2.setVariableValue(vname3, Double.valueOf(vvalue3));
                    }
                }
            }
            String answer = Float.toString((float) f2.evaluate());
            Display_out.setText(answer);
        }   
      

    if(jTextArea2.getText().equals("--No history to show--")){
           System.out.println("Detected");
           jTextArea2.setText(formula+ " "+ "="+" " + Display_out.getText()+"\n");
       }else{
           jTextArea2.setText(jTextArea2.getText()+formula+ " "+ "="+" " + Display_out.getText()+"\n");
       }
        //jTextArea2.setText(jTextArea2.getText()+formula+ " "+ "="+" " + " " + Display_out.getText()+"\n");       
       
    }//GEN-LAST:event_equalActionPerformed

    catch (Exception dd) {
        Display_out.setText("ERROR");
    }
        }
    private void setVvalues(){
        
    }
    
    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        String Enternumber = Display_in.getText() + "1";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        String Enternumber = Display_in.getText() + "2";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        String Enternumber = Display_in.getText() + "3";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_threeActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
       String Enternumber = Display_in.getText() + "+";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_plusActionPerformed

    private void factorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialActionPerformed
        String Enternumber = Display_in.getText() + "!";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_factorialActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
       String Enternumber = Display_in.getText() + "4";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        String Enternumber = Display_in.getText() + "5";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
         String Enternumber = Display_in.getText() + "6";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_sixActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        String Enternumber = Display_in.getText() + "-";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_minusActionPerformed

    private void LOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGActionPerformed
        String Enternumber = Display_in.getText() + "ln(";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_LOGActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
         String Enternumber = Display_in.getText() + "7";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
       String Enternumber = Display_in.getText() + "8";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
       String Enternumber = Display_in.getText() + "9";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_nineActionPerformed

    private void multipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipeActionPerformed
        String Enternumber = Display_in.getText() + "*";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_multipeActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        String Enternumber = Display_in.getText() + "/";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_divideActionPerformed

    private void modificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificationActionPerformed
        String Enternumber = Display_in.getText() + " mod ";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_modificationActionPerformed

    private void intergrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intergrationActionPerformed
        
      JTextField varField = new JTextField(5);  
      JTextField upperField = new JTextField(5);
      JTextField lowerField = new JTextField(5);
      
      JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("Enter Integration Variable:"));
      myPanel.add(varField);
      myPanel.add(Box.createHorizontalStrut(15));
      myPanel.add(new JLabel("Enter Upper Bound:"));
      myPanel.add(upperField);
      myPanel.add(Box.createHorizontalStrut(15)); // a spacer
      myPanel.add(new JLabel("Enter Lower Bound:"));
      myPanel.add(lowerField);
      
      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter Variable and variable bounds", JOptionPane.OK_CANCEL_OPTION);
      if (result == JOptionPane.OK_OPTION) {
         this.upperbound = Double.valueOf(upperField.getText());
         this.lowerbound = Double.valueOf(lowerField.getText());
         this.variablebound = varField.getText().charAt(0);
         Integrationflag = true;
         
         String Enternumber = Display_in.getText() + "∫()d"+variablebound;
        Display_in.setText(Enternumber);
        }
    }//GEN-LAST:event_intergrationActionPerformed

    private void e_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_valueActionPerformed
        String Enternumber = Display_in.getText() + "e";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_e_valueActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        String Enternumber = Display_in.getText() + "^2";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_squareActionPerformed

    private void ten_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten_powerActionPerformed
         String Enternumber = Display_in.getText() + "10^";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_ten_powerActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
         String Enternumber = Display_in.getText() + "sin(";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
          String Enternumber = Display_in.getText() + "cos(";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
       String Enternumber = Display_in.getText() + "tan(";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_tanActionPerformed

    private void cudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cudeActionPerformed
         String Enternumber = Display_in.getText() + "^3";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_cudeActionPerformed

    private void any_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_any_powerActionPerformed
         String Enternumber = Display_in.getText() + "^";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_any_powerActionPerformed

    private void rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootActionPerformed
         String Enternumber = Display_in.getText() + "√(";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_rootActionPerformed

    private void precentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precentageActionPerformed
         String Enternumber = Display_in.getText() + "%";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_precentageActionPerformed

    private void bracket_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracket_OActionPerformed
         String Enternumber = Display_in.getText() + ")";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_bracket_OActionPerformed

    private void bracket_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracket_CActionPerformed
         String Enternumber = Display_in.getText() + "(";
        Display_in.setText(Enternumber);
    }//GEN-LAST:event_bracket_CActionPerformed

    private void up_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_downActionPerformed
        Display_in.setText("1/("+Display_in.getText()+")");
    }//GEN-LAST:event_up_downActionPerformed

    private void graph_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graph_buttonActionPerformed
         String str = Display_in.getText();
        GraphDisplay ob = new GraphDisplay(str);
        ob.setVisible(true);
        dispose();
     
       
    }//GEN-LAST:event_graph_buttonActionPerformed

    private void manage_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_vActionPerformed
      JTextField xField = new JTextField(5);
      JTextField yField = new JTextField(5);

      JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("Enter Variable:"));
      myPanel.add(xField);
      myPanel.add(Box.createHorizontalStrut(15)); // a spacer
      myPanel.add(new JLabel("Enter value:"));
      myPanel.add(yField);

      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter Variable and  Values", JOptionPane.OK_CANCEL_OPTION);
      if (result == JOptionPane.OK_OPTION) {
         
         
         if(flag1 == false){
            vname1 = xField.getText();
            vvalue1 = yField.getText();
            flag1 = true;
            jTextArea1.setText(vname1+ "="+ vvalue1);
         } else if(flag2 == false){
            vname2 = xField.getText();
            vvalue2 = yField.getText();
            flag2 = true;
           jTextArea1.setText(jTextArea1.getText()+"\n"+vname2+ "="+ vvalue2);
         } else if(flag3 == false){
            vname3 = xField.getText();
            vvalue3 = yField.getText();
            flag3 = true;
           jTextArea1.setText(jTextArea1.getText()+"\n"+vname3+ "="+ vvalue3);
         } else {
             JOptionPane.showMessageDialog(clear, "Sorry! Maximum variable limit reached");
         }
         
      }
      
    }//GEN-LAST:event_manage_vActionPerformed

    private void getvariables(){
        
    }
    private void clear_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_entryActionPerformed
        Display_in.setText("");
         Display_out.setText("");
    }//GEN-LAST:event_clear_entryActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        tempsave();
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        Display_in.setText("");
        Display_out.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
       tempload();       
    }//GEN-LAST:event_loadActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
        BasicCalculator ob = new BasicCalculator();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_standardActionPerformed

    private void advanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceActionPerformed
        AdvancedCalculator ob = new AdvancedCalculator();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_advanceActionPerformed

    private void graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphActionPerformed
       GraphDisplay ob = new GraphDisplay();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_graphActionPerformed

    private void Display_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Display_inActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        save();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        load();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextArea1.setText("");
      
      vname1 = "";
      vvalue1 = "";
      flag1 = false;
       vname2 = "";
      vvalue2 = "";
      flag2 = false;
       vname3 = "";
      vvalue3 = "";
      flag3 = false;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextArea2.setText("--No history to show--");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Display_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Display_inKeyPressed
        int keyCode = evt.getKeyCode();
      if(keyCode == KeyEvent.VK_ENTER){
          String str = Display_in.getText();
       FormulaElement f = new FormulaElement() {};
       FormulaElement f2 = f.parseFormula(str,0,0,'x');           
       String answer = Float.toString((float) f2.evaluate());
       Display_out.setText(answer);
      }
      if(keyCode == KeyEvent.VK_BACK_SPACE){
           Display_in.setText (Display_in.getText ().substring (0, Display_in.getText ().length () - 1));
          
      }
      
    }//GEN-LAST:event_Display_inKeyPressed

    
    
    /**
     * @param args the command line arguments
     */
    private HashMap<String, String> temp = new HashMap<String, String>();
    
    
    public void tempsave(){
       String formula = Display_in.getText();
       String fname = (JOptionPane.showInputDialog("Enter Your Formula Name"));
        if(!temp.containsKey(fname)){
            temp.put(fname, formula);
        }
        else{
            int a=JOptionPane.showConfirmDialog(null,"Do you want to overwrite?");
            if(a==JOptionPane.YES_OPTION){
                temp.put(fname, formula);
            }
            if(a==JOptionPane.NO_OPTION){
                fname = (JOptionPane.showInputDialog("Enter a new Formula Name"));
                temp.put(fname, formula);
            }
        }
        
        jTextArea2.setText(jTextArea2.getText()+ "Saved "+fname.toLowerCase()+"() "+"= "+formula+"\n");
    }
    
    public void tempload(){
        String fname = (JOptionPane.showInputDialog("Enter the Formula Name "));
        String formula = temp.get(fname);
        Display_in.setText(formula);
    }
    
    public void save(){
            String saveformula = Display_in.getText();
           String fname = (JOptionPane.showInputDialog("Enter Your Formula Name"));
            JFileChooser jfc = new
            JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            jfc.setDialogTitle("Choose a directory to save your file: ");
            jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int returnValue = jfc.showSaveDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                if (jfc.getSelectedFile().isDirectory()) {
                System.out.println("You selected the directory: " + jfc.getSelectedFile());
                }
            }
            try {
            FileWriter fw = new FileWriter(jfc.getSelectedFile() + "\\" + fname + ".txt");
            fw.write(saveformula);
            fw.close();
            } catch (Exception e) {
            System.out.println(e);
            }
            }
    
    public void load(){
        String userhome = System.getProperty("user.home");
        JFileChooser fc = new JFileChooser(userhome +"\\Desktop");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        fc.setFileFilter(filter);
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        int returnVal = fc.showOpenDialog(frame);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        try {
        BufferedReader input = new BufferedReader(new InputStreamReader(
        new FileInputStream(file)));
        Display_in.read(input, "READING FILE");
        } catch (Exception e) {
        e.printStackTrace();
        }
        } else {
        System.out.println("Operation is CANCELLED");
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvancedCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvancedCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvancedCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvancedCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancedCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display_in;
    private javax.swing.JTextField Display_out;
    private javax.swing.JButton LOG;
    private javax.swing.JButton advance;
    private javax.swing.JButton any_power;
    private javax.swing.JButton bracket_C;
    private javax.swing.JButton bracket_O;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear_entry;
    private javax.swing.JButton cos;
    private javax.swing.JButton cude;
    private javax.swing.JButton decimal_point;
    private javax.swing.JButton delete;
    private javax.swing.JButton divide;
    private javax.swing.JButton e_value;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton factorial;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton graph;
    private javax.swing.JButton graph_button;
    private javax.swing.JScrollPane hscroll;
    private javax.swing.JButton intergration;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton load;
    private javax.swing.JButton manage_v;
    private javax.swing.JButton minus;
    private javax.swing.JButton modification;
    private javax.swing.JButton multipe;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton pie;
    private javax.swing.JButton plus;
    private javax.swing.JButton precentage;
    private javax.swing.JButton root;
    private javax.swing.JButton save;
    private javax.swing.JButton seven;
    private javax.swing.JButton sin;
    private javax.swing.JButton six;
    private javax.swing.JButton square;
    private javax.swing.JButton standard;
    private javax.swing.JButton tan;
    private javax.swing.JButton ten_power;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton up_down;
    private javax.swing.JLabel var_meg;
    private javax.swing.JLabel var_meg1;
    private javax.swing.JScrollPane vscroll;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
