/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectWiCaDi;

import java.awt.event.KeyEvent;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

public class BasicCalculator extends javax.swing.JFrame {

    
    public BasicCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        equal = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        decimal_point = new javax.swing.JButton();
        root = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        three = new javax.swing.JButton();
        precentage = new javax.swing.JButton();
        squre = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        six = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        multipe = new javax.swing.JButton();
        jDisplay_in = new javax.swing.JTextField();
        jDisplay_out = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        advance = new javax.swing.JButton();
        standard = new javax.swing.JButton();
        graph = new javax.swing.JButton();
        Bracket_close = new javax.swing.JButton();
        clear_entry = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clear1 = new javax.swing.JButton();
        Bracket_open = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 750));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 750));

        equal.setBackground(new java.awt.Color(204, 204, 204));
        equal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete.setText("DEL");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(31, 31, 31));
        zero.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        zero.setForeground(new java.awt.Color(255, 255, 255));
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        decimal_point.setBackground(new java.awt.Color(204, 204, 204));
        decimal_point.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        decimal_point.setText(".");
        decimal_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimal_pointActionPerformed(evt);
            }
        });

        root.setBackground(new java.awt.Color(204, 204, 204));
        root.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        root.setLabel("√");
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(31, 31, 31));
        one.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        one.setForeground(new java.awt.Color(255, 255, 255));
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(31, 31, 31));
        two.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        two.setForeground(new java.awt.Color(255, 255, 255));
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(204, 204, 204));
        plus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(31, 31, 31));
        three.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        three.setForeground(new java.awt.Color(255, 255, 255));
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        precentage.setBackground(new java.awt.Color(204, 204, 204));
        precentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        precentage.setText("%");
        precentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precentageActionPerformed(evt);
            }
        });

        squre.setBackground(new java.awt.Color(204, 204, 204));
        squre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        squre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/1608861-64 (1).png"))); // NOI18N
        squre.setActionCommand("sqr");
        squre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squreActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(31, 31, 31));
        seven.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        seven.setForeground(new java.awt.Color(255, 255, 255));
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(31, 31, 31));
        four.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        four.setForeground(new java.awt.Color(255, 255, 255));
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(31, 31, 31));
        five.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        five.setForeground(new java.awt.Color(255, 255, 255));
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(31, 31, 31));
        eight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eight.setForeground(new java.awt.Color(255, 255, 255));
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(31, 31, 31));
        nine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nine.setForeground(new java.awt.Color(255, 255, 255));
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(31, 31, 31));
        six.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        six.setForeground(new java.awt.Color(255, 255, 255));
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        divide.setBackground(new java.awt.Color(204, 204, 204));
        divide.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        minus.setBackground(new java.awt.Color(204, 204, 204));
        minus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        multipe.setBackground(new java.awt.Color(204, 204, 204));
        multipe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        multipe.setText("*");
        multipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipeActionPerformed(evt);
            }
        });

        jDisplay_in.setBackground(new java.awt.Color(255, 255, 255));
        jDisplay_in.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jDisplay_in.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jDisplay_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplay_inActionPerformed(evt);
            }
        });
        jDisplay_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDisplay_inKeyPressed(evt);
            }
        });

        jDisplay_out.setEditable(false);
        jDisplay_out.setBackground(new java.awt.Color(255, 255, 255));
        jDisplay_out.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        jDisplay_out.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/pgg.jpg"))); // NOI18N
        jLabel1.setName(""); // NOI18N

        advance.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        advance.setText("Advanced Calculator");
        advance.setPreferredSize(new java.awt.Dimension(200, 30));
        advance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceActionPerformed(evt);
            }
        });

        standard.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        standard.setText("Basic Calculator");
        standard.setPreferredSize(new java.awt.Dimension(200, 30));
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        graph.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        graph.setText("Graph Display");
        graph.setPreferredSize(new java.awt.Dimension(200, 30));
        graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphActionPerformed(evt);
            }
        });

        Bracket_close.setBackground(new java.awt.Color(31, 31, 31));
        Bracket_close.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Bracket_close.setForeground(new java.awt.Color(255, 255, 255));
        Bracket_close.setText(")");
        Bracket_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bracket_closeActionPerformed(evt);
            }
        });

        clear_entry.setBackground(new java.awt.Color(31, 31, 31));
        clear_entry.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clear_entry.setForeground(new java.awt.Color(255, 255, 255));
        clear_entry.setText("CE");
        clear_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_entryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/font.jpg"))); // NOI18N
        jLabel2.setName(""); // NOI18N

        clear1.setBackground(new java.awt.Color(31, 31, 31));
        clear1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clear1.setForeground(new java.awt.Color(255, 255, 255));
        clear1.setText("C");
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        Bracket_open.setBackground(new java.awt.Color(31, 31, 31));
        Bracket_open.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Bracket_open.setForeground(new java.awt.Color(255, 255, 255));
        Bracket_open.setText("(");
        Bracket_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bracket_openActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(standard, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(graph, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDisplay_in)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(decimal_point, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bracket_open, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bracket_close, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(precentage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(squre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(multipe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jDisplay_out, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jDisplay_in, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDisplay_out, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bracket_close, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bracket_open, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(precentage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(multipe, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decimal_point, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(squre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
    try {   
       String str = jDisplay_in.getText();
       FormulaElement f = new FormulaElement() {};
       FormulaElement f2 = f.parseFormula(str,0,0,'x');           
       String answer = Float.toString((float) f2.evaluate());
       jDisplay_out.setText(answer);
    }catch (Exception dd) {
        jDisplay_out.setText("ERROR");
    }
    }//GEN-LAST:event_equalActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        jDisplay_in.setText (jDisplay_in.getText ().substring (0, jDisplay_in.getText ().length () - 1));
    }//GEN-LAST:event_deleteActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
       
        String Enternumber = jDisplay_in.getText() + "0";
        jDisplay_in.setText(Enternumber);

    }//GEN-LAST:event_zeroActionPerformed

    private void decimal_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimal_pointActionPerformed
        
       String Enternumber = jDisplay_in.getText() + ".";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_decimal_pointActionPerformed

    private void rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootActionPerformed
       
        String Enteroperation = jDisplay_in.getText() + "√()";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_rootActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        
        String Enternumber = jDisplay_in.getText() + "1";
        jDisplay_in.setText(Enternumber);
        
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        
        String Enternumber = jDisplay_in.getText() + "2";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_twoActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        
        String Enteroperation = jDisplay_in.getText() + "+";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_plusActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
       
        String Enternumber = jDisplay_in.getText() + "3";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_threeActionPerformed

    private void precentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precentageActionPerformed
        
        String Enteroperation = jDisplay_in.getText() + "%";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_precentageActionPerformed

    private void squreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squreActionPerformed
       
        String Enteroperation = jDisplay_in.getText() + "^2";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_squreActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        
        String Enternumber = jDisplay_in.getText() + "7";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_sevenActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        
        String Enternumber = jDisplay_in.getText() + "4";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
         
        String Enternumber = jDisplay_in.getText() + "5";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_fiveActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        
        String Enternumber = jDisplay_in.getText() + "8";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        
        String Enternumber = jDisplay_in.getText() + "9";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_nineActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
       
        String Enternumber = jDisplay_in.getText() + "6";
        jDisplay_in.setText(Enternumber);
    }//GEN-LAST:event_sixActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        
        String Enteroperation = jDisplay_in.getText() + "/";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_divideActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
       
        String Enteroperation = jDisplay_in.getText() + "-";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_minusActionPerformed

    private void multipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipeActionPerformed
       
        String Enteroperation = jDisplay_in.getText() + "*";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_multipeActionPerformed

    private void jDisplay_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplay_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDisplay_inActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
        
    }//GEN-LAST:event_standardActionPerformed

    private void advanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceActionPerformed
        AdvancedCalculator ob = new AdvancedCalculator();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_advanceActionPerformed

    private void graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphActionPerformed
         GraphDisplay ob = new GraphDisplay();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_graphActionPerformed

    private void Bracket_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bracket_closeActionPerformed
        String Enteroperation = jDisplay_in.getText() + ")";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_Bracket_closeActionPerformed

    private void clear_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_entryActionPerformed
      jDisplay_in.setText("");
        jDisplay_out.setText("");
    }//GEN-LAST:event_clear_entryActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        jDisplay_in.setText("");
        jDisplay_out.setText("");
    }//GEN-LAST:event_clear1ActionPerformed

    private void Bracket_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bracket_openActionPerformed
        String Enteroperation = jDisplay_in.getText() + "(";
        jDisplay_in.setText(Enteroperation);
    }//GEN-LAST:event_Bracket_openActionPerformed

    private void jDisplay_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDisplay_inKeyPressed
       int keyCode = evt.getKeyCode();
      if(keyCode == KeyEvent.VK_ENTER){
          String str = jDisplay_in.getText();
       FormulaElement f = new FormulaElement() {};
       FormulaElement f2 = f.parseFormula(str,0,0,'x');           
       String answer = Float.toString((float) f2.evaluate());
       jDisplay_out.setText(answer);
      }
      if(keyCode == KeyEvent.VK_BACK_SPACE){
           jDisplay_in.setText (jDisplay_in.getText ().substring (0, jDisplay_in.getText ().length () - 1));
          
      }
       if(keyCode == KeyEvent.VK_1){
            String Enternumber = jDisplay_in.getText() + "1";
        jDisplay_in.setText(Enternumber);;
          
      }
      
    }//GEN-LAST:event_jDisplay_inKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {

UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicCalculator().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bracket_close;
    private javax.swing.JButton Bracket_open;
    private javax.swing.JButton advance;
    private javax.swing.JButton clear1;
    private javax.swing.JButton clear_entry;
    private javax.swing.JButton decimal_point;
    private javax.swing.JButton delete;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton graph;
    private javax.swing.JTextField jDisplay_in;
    private javax.swing.JTextField jDisplay_out;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minus;
    private javax.swing.JButton multipe;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton plus;
    private javax.swing.JButton precentage;
    private javax.swing.JButton root;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton squre;
    private javax.swing.JButton standard;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
