/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectWiCaDi;

import static demo.BubbleChartDemo1.createDataset;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import org.apache.commons.io.FileUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author sandalu
 */
public class GraphDisplay extends javax.swing.JFrame {

    /**
     * Creates new form Graph
     */
    
    private String vname1;
    private String vvalue1;
    boolean flag1 = false;
    
    private String vname2;
    private String vvalue2;
    boolean flag2 = false;
    
    private String vname3;
    private String vvalue3;
    boolean flag3 = false;
    
    StringBuilder st = new StringBuilder();
    
    
    public GraphDisplay() {
        initComponents();
    }
    
    public GraphDisplay(String formula){
        initComponents();
        formula_display.setText(formula);
    }
    
    final XYSeriesCollection dataset = new XYSeriesCollection();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        advance = new javax.swing.JButton();
        basic = new javax.swing.JButton();
        graph = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        v_to = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        formula_display = new javax.swing.JTextField();
        var = new javax.swing.JLabel();
        genarate = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        manage = new javax.swing.JButton();
        find_area = new javax.swing.JButton();
        load = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        v_to1 = new javax.swing.JTextField();
        v_to2 = new javax.swing.JTextField();
        jTextArea1 = new javax.swing.JTextArea();
        var_meg = new javax.swing.JLabel();
        v_to3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/font.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/pgg.jpg"))); // NOI18N

        advance.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        advance.setText("Advanced Calculator");
        advance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceActionPerformed(evt);
            }
        });

        basic.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        basic.setText("Basic Calculator");
        basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicActionPerformed(evt);
            }
        });

        graph.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        graph.setText("Graph Display");
        graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        v_to.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        v_to.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        v_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_toActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Formula");

        formula_display.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 20)); // NOI18N
        formula_display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        formula_display.setToolTipText("");
        formula_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formula_displayActionPerformed(evt);
            }
        });

        var.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        var.setForeground(new java.awt.Color(255, 255, 255));
        var.setText("Independent Variable ");

        genarate.setBackground(new java.awt.Color(31, 31, 31));
        genarate.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 20)); // NOI18N
        genarate.setForeground(new java.awt.Color(255, 255, 255));
        genarate.setText("Genarate");
        genarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genarateActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(31, 31, 31));
        clear.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 20)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        manage.setBackground(new java.awt.Color(31, 31, 31));
        manage.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        manage.setForeground(new java.awt.Color(255, 255, 255));
        manage.setText("Add Constant Varibles");
        manage.setActionCommand("");
        manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageActionPerformed(evt);
            }
        });

        find_area.setBackground(new java.awt.Color(31, 31, 31));
        find_area.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 20)); // NOI18N
        find_area.setForeground(new java.awt.Color(255, 255, 255));
        find_area.setText("Find Area");
        find_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_areaActionPerformed(evt);
            }
        });

        load.setBackground(new java.awt.Color(204, 204, 204));
        load.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        load.setText("Load graph");
        load.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        save.setText("Save graph");
        save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To -:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("From -:");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Range");

        v_to1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        v_to1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        v_to1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_to1ActionPerformed(evt);
            }
        });

        v_to2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        v_to2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        v_to2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_to2ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        var_meg.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        var_meg.setForeground(new java.awt.Color(255, 255, 255));
        var_meg.setText("      Constant Variables");

        v_to3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        v_to3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        v_to3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_to3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Y=");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectWiCaDi/informauion.jpg"))); // NOI18N
        jButton6.setToolTipText("Declair constant variables of the graph here. There can be only one free variable in a 2D graph.");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(315, 315, 315)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(basic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(formula_display, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(v_to1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(var, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(v_to, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jLabel9)))
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(v_to2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(advance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(v_to3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(find_area, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(genarate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(manage, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextArea1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGap(0, 62, Short.MAX_VALUE)
                                                    .addComponent(var_meg)))))
                                    .addGap(28, 28, 28)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(save)
                        .addGap(20, 20, 20)
                        .addComponent(load))
                    .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formula_display, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v_to1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v_to, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v_to2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(genarate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(var))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manage, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(var_meg)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(find_area, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v_to3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(load, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void advanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceActionPerformed
      AdvancedCalculator ob = new AdvancedCalculator();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_advanceActionPerformed

    private void basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicActionPerformed
        BasicCalculator ob = new BasicCalculator();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_basicActionPerformed

    private void v_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_toActionPerformed

    private void formula_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formula_displayActionPerformed

    }//GEN-LAST:event_formula_displayActionPerformed

    private void genarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genarateActionPerformed
try{      
        JFreeChart xylineChart = ChartFactory.createXYLineChart(
                "Graph Display",
                "X Axis",
                "Y Axis",
                createDataset(),
                PlotOrientation.VERTICAL,
                true, true, false);

        ChartPanel chartPanel = new ChartPanel(xylineChart);
//      chartPanel.setPreferredSize( new java.awt.Dimension( 560 , 367 ) );

        XYPlot plot = xylineChart.getXYPlot();
        plot.setRangeGridlinePaint(Color.blue);
        
        
        XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
        renderer.setSeriesPaint(0, Color.BLACK);
        renderer.setSeriesStroke(0, new BasicStroke(1.0f));
        //plot.setRenderer(renderer);
        // setContentPane( chartPanel ); 

//      ChartPanel linePanel = new ChartPanel(xylineChart);
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.removeAll();
        jPanel2.add(chartPanel, BorderLayout.CENTER);
        jPanel2.validate();
        
        
      }catch (Exception dd) {
        formula_display.setText("ERROR");
    }  
        
          
    }//GEN-LAST:event_genarateActionPerformed
 private XYDataset createDataset( ) {
     
        String s = formula_display.getText();
        char var = v_to1.getText().charAt(0);
        int start = Integer.valueOf(v_to.getText());
        int end = Integer.valueOf(v_to2.getText());
        
        final XYSeries xydataset = new XYSeries( s );
        for(int i=start; i<=end;i++){
            FormulaElement f = new FormulaElement() {};
            FormulaElement f2 = f.parseFormula(s,0,0,var); 
            f2.setVariableValue(String.valueOf(var), i);
            if(this.flag1 == true){
                f2.setVariableValue(vname1, Double.valueOf(vvalue1));
                if(this.flag2 == true){
                    f2.setVariableValue(vname2, Double.valueOf(vvalue2));
                    if(this.flag3 == true){
                        f2.setVariableValue(vname3, Double.valueOf(vvalue3));
                    }
                }
            }
           double answer = f2.evaluate();
           xydataset.add( i ,answer ); 
           st.append(i+",");
           int ans = (int) Math.round(answer);
           st.append(ans);
           st.append("\n");
      }              
      
                
      dataset.addSeries( xydataset );  
      return dataset;
   }
     
   
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        jPanel2.removeAll();
        jPanel2.updateUI();
        dataset.removeAllSeries();
        v_to3.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageActionPerformed
      JTextField xField = new JTextField(5);
      JTextField yField = new JTextField(5);

      JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("Enter Variable:"));
      myPanel.add(xField);
      myPanel.add(Box.createHorizontalStrut(15)); // a spacer
      myPanel.add(new JLabel("Enter value:"));
      myPanel.add(yField);

      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter Variable and  Values", JOptionPane.OK_CANCEL_OPTION);
      if (result == JOptionPane.OK_OPTION) {
        
         
         if(flag1 == false){
            vname1 = xField.getText();
            vvalue1 = yField.getText();
            flag1 = true;
            jTextArea1.setText(vname1+ "="+ vvalue1);
         } else if(flag2 == false){
            vname2 = xField.getText();
            vvalue2 = yField.getText();
            flag2 = true;
            jTextArea1.setText(jTextArea1.getText()+"\n"+vname2+ "="+ vvalue2);
         } else if(flag3 == false){
            vname3 = xField.getText();
            vvalue3 = yField.getText();
            flag3 = true;
            jTextArea1.setText(jTextArea1.getText()+"\n"+vname3+ "="+ vvalue3);
         } else {
             JOptionPane.showMessageDialog(clear, "Sorry! Maximum variable limit reached");
         }
      }
      
      
    }//GEN-LAST:event_manageActionPerformed

    private void find_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_areaActionPerformed
        int upperbound = Integer.valueOf(v_to.getText());
        int lowerbound = Integer.valueOf(v_to2.getText());
        
        //add variable name here
        
        char var = v_to1.getText().charAt(0);
        
        String str = "∫("+formula_display.getText()+")d"+var;
        FormulaElement f = new FormulaElement() {};
        FormulaElement f2 = f.parseFormula(str, upperbound, lowerbound, var);
       
        f2.setVariableValue("e", 2.718);
        f2.setVariableValue("π", 3.141);    
       
        if(this.flag1 == true){
            f2.setVariableValue(vname1, Double.valueOf(vvalue1));
            if(this.flag2 == true){
                f2.setVariableValue(vname2, Double.valueOf(vvalue2));
                if(this.flag2 == true){
                    f2.setVariableValue(vname3, Double.valueOf(vvalue3));
                }
            }
        }
        
        String answer = Float.toString((float) f2.evaluate());
        double ans = Double.valueOf(answer);
        if(ans<0){
            ans=ans*-1;
            answer = String.valueOf(ans);
        }
        v_to3.setText(answer);
    }//GEN-LAST:event_find_areaActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        
        jPanel2.removeAll();
        jPanel2.updateUI();
        dataset.removeAllSeries();
        
        String userhome = System.getProperty("user.home");
        JFileChooser fc = new JFileChooser(userhome +"\\Desktop");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "csv", "text");
        fc.setFileFilter(filter);
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        int returnVal = fc.showOpenDialog(frame);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();

        String str = null;
            try {
                str = FileUtils.readFileToString(file);
            } catch (IOException ex) {
                Logger.getLogger(GraphDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            String f = file.getName();
            final XYSeries xydataset = new XYSeries(f);
            Vector<Object> vecArr = new Vector<>();
            StringTokenizer tokenizer = new StringTokenizer(str, ",\n", false);
            while (tokenizer.hasMoreTokens()) {
                String token = tokenizer.nextToken();
                vecArr.add(token);
            }
            System.out.println(vecArr);
            for(int i =0;i<vecArr.size()-1;i=i+2){
                int no1 = Integer.valueOf((String) vecArr.get(i));
                int no2 = Integer.valueOf((String) vecArr.get(i+1));
                xydataset.add(no1,no2);
            }
            dataset.addSeries( xydataset );
        
        
        JFreeChart xylineChart = ChartFactory.createXYLineChart(
                "Graph Display",
                "X Axis",
                "Y Axis",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false);

        ChartPanel chartPanel = new ChartPanel(xylineChart);
//      chartPanel.setPreferredSize( new java.awt.Dimension( 560 , 367 ) );

        XYPlot plot = xylineChart.getXYPlot();
        plot.setRangeGridlinePaint(Color.blue);
        
        
        XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
        renderer.setSeriesPaint(0, Color.BLACK);
        renderer.setSeriesStroke(0, new BasicStroke(1.0f));
        //plot.setRenderer(renderer);
        // setContentPane( chartPanel ); 

//      ChartPanel linePanel = new ChartPanel(xylineChart);
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.removeAll();
        jPanel2.add(chartPanel, BorderLayout.CENTER);
        jPanel2.validate();
        }
    }//GEN-LAST:event_loadActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
      String fname = (JOptionPane.showInputDialog("Enter Your Formula Name"));
            
            JFileChooser jfc = new
            JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            jfc.setDialogTitle("Choose a directory to save your file: ");
            jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int returnValue = jfc.showSaveDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                if (jfc.getSelectedFile().isDirectory()) {
                System.out.println("You selected the directory: " + jfc.getSelectedFile());
                }
            }
            try {
            FileWriter fw = new FileWriter(jfc.getSelectedFile() + "\\"+fname+".csv");
            
            
            fw.write(st.toString());
            fw.close();
            } catch (Exception e) {
            System.out.println(e);
            }
    }//GEN-LAST:event_saveActionPerformed

    private void v_to1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_to1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_to1ActionPerformed

    private void v_to2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_to2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_to2ActionPerformed

    private void v_to3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_to3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_to3ActionPerformed

    private void graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graphActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        jTextArea1.setText("");
      
      vname1 = "";
      vvalue1 = "";
      flag1 = false;
       vname2 = "";
      vvalue2 = "";
      flag2 = false;
       vname3 = "";
      vvalue3 = "";
      flag3 = false;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advance;
    private javax.swing.JButton basic;
    private javax.swing.JButton clear;
    private javax.swing.JButton find_area;
    private javax.swing.JTextField formula_display;
    private javax.swing.JButton genarate;
    private javax.swing.JButton graph;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton load;
    private javax.swing.JButton manage;
    private javax.swing.JButton save;
    private javax.swing.JTextField v_to;
    private javax.swing.JTextField v_to1;
    private javax.swing.JTextField v_to2;
    private javax.swing.JTextField v_to3;
    private javax.swing.JLabel var;
    private javax.swing.JLabel var_meg;
    // End of variables declaration//GEN-END:variables
}
